// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rent_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RentInfo _$RentInfoFromJson(Map<String, dynamic> json) => RentInfo(
      json['houseResourceId'] as String?,
      json['photo'] as String?,
      json['estateName'] as String?,
      json['stageName'] as String?,
      json['buildingName'] as String?,
      json['title'] as String?,
      json['floorLevel'] as String?,
      json['floorName'] as String?,
      json['roomName'] as String?,
      json['guestRoom'] as int?,
      (json['roomArea'] as num?)?.toDouble(),
      (json['buildArea'] as num?)?.toDouble(),
      json['partition'] as String?,
      json['propertyType'] as String?,
      json['location'] as String?,
      json['label'] as String?,
      (json['price'] as num?)?.toDouble(),
      json['openType'] as bool?,
      json['guestRoomX'] as int?,
      json['suite'] as int?,
      (json['roomAreaX'] as num?)?.toDouble(),
      (json['buildAreaX'] as num?)?.toDouble(),
      (json['priceX'] as num?)?.toDouble(),
      json['time'] as int?,
      json['status'] as int?,
      json['advertUrl'] as String?,
      json['advertLink'] as String?,
      json['displayStatus'] as String?,
      json['city'] as String?,
      json['overseas'] as bool?,
      json['advertId'] as String?,
      json['vedio'] as String?,
      json['shopPath'] as String?,
      json['carportNumber'] as String?,
    );

Map<String, dynamic> _$RentInfoToJson(RentInfo instance) => <String, dynamic>{
      'houseResourceId': instance.houseResourceId,
      'photo': instance.photo,
      'estateName': instance.estateName,
      'stageName': instance.stageName,
      'buildingName': instance.buildingName,
      'title': instance.title,
      'floorLevel': instance.floorLevel,
      'floorName': instance.floorName,
      'roomName': instance.roomName,
      'guestRoom': instance.guestRoom,
      'roomArea': instance.roomArea,
      'buildArea': instance.buildArea,
      'partition': instance.partition,
      'propertyType': instance.propertyType,
      'location': instance.location,
      'label': instance.label,
      'price': instance.price,
      'openType': instance.openType,
      'guestRoomX': instance.guestRoomX,
      'suite': instance.suite,
      'roomAreaX': instance.roomAreaX,
      'buildAreaX': instance.buildAreaX,
      'priceX': instance.priceX,
      'time': instance.time,
      'status': instance.status,
      'advertUrl': instance.advertUrl,
      'advertLink': instance.advertLink,
      'displayStatus': instance.displayStatus,
      'city': instance.city,
      'overseas': instance.overseas,
      'advertId': instance.advertId,
      'vedio': instance.vedio,
      'shopPath': instance.shopPath,
      'carportNumber': instance.carportNumber,
    };
